micronaut:
  application:
    name: demo
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://dbpostgresql:5432/postgres
    username: admin
    password: admin
    schema-generate: CREATE_DROP
jpa:
  default:
    compile-time-hibernate-proxies: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
jpa.default.properties.hibernate.hbm2ddl.auto: update
hibernate:
  bytecode:
    provider: none
    use_reflection_optimizer: false

